# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("abhere2.abhere.top", false);
user_pref("abhere2.folderURI.livemark", "rdf:#$iHMkC");
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("allowclipboardhelper.tabs.disabled", false);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1194030660);
user_pref("app.update.lastUpdateTime.background-update-timer", 1194030660);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1194030660);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1194021812);
user_pref("bcpm.Button.Shown", true);
user_pref("browser.cache.disk.capacity", 1);
user_pref("browser.cache.disk_cache_ssl", true);
user_pref("browser.cache.memory.capacity", 65536);
user_pref("browser.download.dir", "H:");
user_pref("browser.download.hide_plugins_without_extensions", false);
user_pref("browser.download.lastDir", "E:\\EigeneDateien\\jondos\\Coding\\Extensions");
user_pref("browser.download.manager.showAlertOnComplete", false);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.feeds.handler", "bookmarks");
user_pref("browser.feeds.handler.default", "bookmarks");
user_pref("browser.feeds.handlers.webservice", "http://www.bloglines.com/login?r=/sub/%s");
user_pref("browser.feeds.showFirstRunUI", false);
user_pref("browser.history_expire_days", 1);
user_pref("browser.history_expire_days.mirror", 1);
user_pref("browser.offline", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.preferences.privacy.selectedTabIndex", 5);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.send_pings", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1.8");
user_pref("browser.startup.page", 0);
user_pref("browser.throbber.url", "http://www.mozilla.org/");
user_pref("browser.turbo.enabled", false);
user_pref("cacheit.firsttime", ".8");
user_pref("calculator.calc_angle", 1);
user_pref("calculator.calc_open", 0);
user_pref("calculator.calc_pad", 0);
user_pref("capability.policy.allowclipboard.Clipboard.cutcopy", "allAccess");
user_pref("capability.policy.allowclipboard.Clipboard.paste", "allAccess");
user_pref("capability.policy.allowclipboard.sites", "");
user_pref("capability.policy.maonoscript.javascript.enabled", "allAccess");
user_pref("capability.policy.maonoscript.sites", "about: chrome: resource:");
user_pref("capability.policy.policynames", "allowclipboard");
user_pref("compact.menu.firstrun", false);
user_pref("cookiesafe.enableFkey", true);
user_pref("cookiesafe.ignoreSub", false);
user_pref("cookiesafe.originalOnly", true);
user_pref("copyplaintext.default", true);
user_pref("copyplaintext.formatting.extra.newline", true);
user_pref("copyplaintext.formatting.extra.space", true);
user_pref("copyplaintext.formatting.trim", true);
user_pref("cutemenus.firstrun", "2.1");
user_pref("cutemenus.observer", "*");
user_pref("cutemenus.skin", false);
user_pref("dom.max_chrome_script_run_time", 60);
user_pref("downbar.function.clearOnClose", true);
user_pref("downbar.function.donateTextInterval", "118967378820900");
user_pref("downbar.function.firstRun", false);
user_pref("downbar.function.keepHistory", false);
user_pref("downbar.function.launchOnClose", true);
user_pref("downbar.function.soundCustomComplete", "file://");
user_pref("downbar.function.useTooltipOpaciF:Seq RDF:about="NC:menu_BookmarksPopup">
  </RDF:Seq>
  <NC:BookmarkSeparator RDF:about="rdf:#$iK1fG"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$iK1fG"
                   NC:Custom="create" />
  <NC:BookmarkSeparator RDF:about="rdf:#$ter6+1"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$ter6+1"
                   NC:Custom="create" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#tinyurl-context-page-menu"
                   NC:Visibility="visible"
                   NC:Name="Create TinyUrl for this Page" />
  <NC:Menu RDF:about="http://home.netscape.com/NC-rdf#cssview-context-menu"
                   NC:Visibility="visible"
                   NC:Name="Externe CSS-Datei anzeigen" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-keywordfield"
                   NC:Visibility="visible"
                   NC:Name="Ein Schlüsselwort für diese Suche hinzufügen..." />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-bookmarkpage"
                   NC:Visibility="visible"
                   NC:Name="Lesezeichen für diese Seite hinzufügen..." />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#translate"
                   NC:Visibility="visible"
                   NC:Name="Aus dem Englischen übersetzen" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-undo"
                   NC:Visibility="visible"
                   NC:Name="Rückgängig" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#fireftpcontentarea"
                   NC:Visibility="visible"
                   NC:Name="View This Page in FireFTP" />
  <RDF:Description RDF:about="http://home.netscape.com/NC-rdf#menu_EditPopup"
                   NC:Name="Bearbeiten" />
  <NC:Menu RDF:about="http://home.netscape.com/NC-rdf#menuedit-contentAreaContextMenu-Cache_View"
                   NC:Visibility="visible"
                   NC:Name="Cache View" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menuedit-tabContextMenu-Alle_Tabs_neu_laden"
                   NC:Visibility="visible"
                   NC:Name="Alle Tabs neu laden" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#javascriptConsole"
                   NC:Visibility="visible"
                   NC:Name="Fehler-Konsole" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menu_inspector"
                   NC:Visibility="visible"
                   NC:Name="DOM Inspector" />
  <NC:BookmarkSeparator RDF:about="rdf:#$wer6+1"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$wer6+1"
                   NC:Custom="create" />
  <NC:BookmarkSeparator RDF:about="rdf:#$EVu8c2"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$EVu8c2"
                   NC:Custom="create" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menuedit-tabContextMenu-Lesezeichen_f252r_alle_offenen_Tabs_hinzuf252gen"
                   NC:Visibility="visible"
                   NC:Name="Lesezeichen für alle offenen Tabs hinzufügen..." />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#tinyurl-context-link-menu"
                   NC:Visibility="visible"
                   NC:Name="Create TinyUrl for this Link" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-zoom-zin"
                   NC:Visibility="visible"
                   NC:Name="+  Grafik vergrößern" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-viewpartialsource-selection"
                   NC:Visibility="visible"
                   NC:Name="Auswahl-Quelltext anzeigen" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#contextArchiveXPI"
                   NC:Name="XPI-Dateien archivieren"
                   NC:Visibility="visible" />
  <NC:BookmarkSeparator RDF:about="rdf:#$gK1fG"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$gK1fG"
                   NC:Custom="ignore" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menu_ToolsPopup-Seiteninformationen"
                   NC:Visibility="visible"
                   NC:Name="Seiteninformationen" />
  <NC:BookmarkSeparator RDF:about="rdf:#$ver6+1"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$ver6+1"
                   NC:Custom="create" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menu_ToolsPopup-Web45Suche"
                   NC:Visibility="visible"
                   NC:Name="Web-Suche" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#cutemenus-options-firefox"
                   NC:Name="CuteMenus Einstellungen"
                   NC:Visibility="hidden" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#tools-menu-Page%20Info"
                   NC:Visibility="visible"
                   NC:Name="Page Info" />
  <NC:Menu RDF:about="http://home.netscape.com/NC-rdf#context-zoomsub"
                   NC:Visibility="visible"
                   NC:Name="Grafik zoomen" />
  <NC:Menu RDF:about="http://home.netscape.com/NC-rdf#tools_theme_switcher"
                   NC:Visibility="visible"
                   NC:Name="Theme wechseln" />
  <NC:Other RDF:about="http://home.netscape.com/NC-rdf#menuedit-contentAreaContextMenu-untitled3"
                   NC:Visibility="hidden"
                   NC:Name="menuedit-contentAreaContextMenu-untitled3" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#tabrenamizer-restore"
                   NC:Visibility="visible"
                   NC:Name="Restore tab titles" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-forward"
                   NC:Visibility="visible"
                   NC:Name="Vor" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#contextPasteAgentBuildId"
                   NC:Name="UserAgent-String/Build ID einfügen"
                   NC:Visibility="hidden" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-cut"
                   NC:Visibility="visible"
                   NC:Name="Ausschneiden" />
  <NC:Menu RDF:about="http://home.netscape.com/NC-rdf#tools_extension_options"
                   NC:Visibility="visible"
                   NC:Name="Erweiterungs-Einstellungen" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#openInNewWindow"
                   NC:Visibility="visible"
                   NC:Name="Öffne Auswahl in neuem Fenster" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-selectall"
                   NC:Visibility="visible"
                   NC:Name="Alles markieren" />
  <RDF:Description RDF:about="http://home.netscape.com/NC-rdf#menu_ToolsPopup"
                   NC:Name="Extras" />
  <RDF:Seq RDF:about="NC:menu_viewPopup">
  </RDF:Seq>
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-bookmarklink"
                   NC:Visibility="visible"
                   NC:Name="Lesezeichen für diesen Link hinzufügen..." />
  <NC:Menu RDF:about="http://home.netscape.com/NC-rdf#spell-dictionaries"
                   NC:Visibility="visible"
                   NC:Name="Sprachen" />
  <NC:BookmarkSeparator RDF:about="rdf:#$tK1fG"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$tK1fG"
                   NC:Custom="create" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#composeMail"
                   NC:Visibility="visible"
                   NC:Name="Erstelle eine E-Mail" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#tabrenamizer-renamethistab"
                   NC:Visibility="visible"
                   NC:Name="Rename this tab..." />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menuedit-tabContextMenu-Neuer_Tab"
                   NC:Visibility="visible"
                   NC:Name="Neuer Tab" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menu_ToolsPopup-Sage"
                   NC:Visibility="visible"
                   NC:Name="Sage" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#save"
                   NC:Visibility="visible"
                   NC:Name="Als Datei speichern..." />
  <NC:BookmarkSeparator RDF:about="rdf:#$per6+1"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$per6+1"
                   NC:Custom="create" />
  <NC:BookmarkSeparator RDF:about="rdf:#$lK1fG"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$lK1fG"
                   NC:Custom="create" />
  <NC:BookmarkSeparator RDF:about="rdf:#$rer6+1"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$rer6+1"
                   NC:Custom="create" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menuedit-tabContextMenu-Reload_All_Tabs"
                   NC:Visibility="visible"
                   NC:Name="Reload All Tabs" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#tools-menu-Web%20Search"
                   NC:Visibility="visible"
                   NC:Name="Web Search" />
  <NC:Menu RDF:about="http://home.netscape.com/NC-rdf#cacheit-contextmenu"
                   NC:Name="CacheIt! More Options"
                   NC:Visibility="hidden" />
  <NC:BookmarkSeparator RDF:about="rdf:#$eK1fG"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$eK1fG"
                   NC:Custom="create" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menu_ToolsPopup-Add45ons"
                   NC:Visibility="visible"
                   NC:Name="Add-ons" />
  <NC:BookmarkSeparator RDF:about="rdf:#$kK1fG"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$kK1fG"
                   NC:Custom="create" />
  <NC:Menu RDF:about="http://home.netscape.com/NC-rdf#tools_edit_my_config"
                   NC:Visibility="visible"
                   NC:Name="Eigene Konfiguration bearbeiten" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-zoom-zout"
                   NC:Visibility="visible"
                   NC:Name="-   Grafik verkleinern" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menuedit-tabContextMenu-New_Tab"
                   NC:Visibility="visible"
                   NC:Name="New Tab" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#menuedit-menuedit-tabContextMenu-Lesezeichen_f252r_diesen_Tab_hinzuf252gen"
                   NC:Visibility="visible"
                   NC:Name="Lesezeichen für diesen Tab hinzufügen..." />
  <RDF:Seq RDF:about="NC:MenuEditRoot">
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#contentAreaContextMenu"/>
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#menu_FilePopup"/>
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#menu_EditPopup"/>
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#menu_viewPopup"/>
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#goPopup"/>
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#menu_BookmarksPopup"/>
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#menu_ToolsPopup"/>
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#menu_HelpPopup"/>
    <RDF:li RDF:resource="http://home.netscape.com/NC-rdf#menuedit-tabContextMenu"/>
  </RDF:Seq>
  <RDF:Description RDF:about="NC:MenuEditRoot"
                   NC:Version="20050202+" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-zoom-zreset"
                   NC:Visibility="visible"
                   NC:Name="&lt;  Grafik zurücksetzen" />
  <RDF:Seq RDF:about="NC:goPopup">
  </RDF:Seq>
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#spell-add-to-dictionary"
                   NC:Visibility="visible"
                   NC:Name="Zu Benutzerwörterbuch hinzufügen" />
  <NC:BookmarkSeparator RDF:about="rdf:#$qer6+1"
                   NC:Visibility="visible"
                   NC:Name="rdf:#$qer6+1"
                   NC:Custom="create" />
  <NC:Menuitem RDF:about="http://home.netscape.com/NC-rdf#context-stop"
                   NC:Visibility="visible"
                   NC:Name="Stopp" />
  <NC:Menuitem RDF:about="http://hom