# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */


user_pref("app.update.auto", false);

user_pref("dwhelper.last-version", "4.9.21");
user_pref("extensions.adblockplus.currentVersion", "2.5.1");
user_pref("noscript.version", "2.6.8.17");
user_pref("extensions.jondofox.profile_version", "2.9.0");

user_pref("browser.startup.homepage_override.mstone", "24.3.0");
user_pref("extensions.lastAppVersion", "24.3.0");
user_pref("extensions.lastPlatformVersion", "24.3.0");

user_pref("general.appname.override", "Netscape");
user_pref("general.appversion.override", "5.0 (X11)");
user_pref("general.buildID.override", "20140131092626");
user_pref("general.oscpu.override", "Linux i686");
user_pref("general.platform.override", "Linux i686");
user_pref("general.productsub.override", "20100101");
user_pref("general.useragent.override", "Mozilla/5.0 (X11; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0");
user_pref("general.useragent.vendor", "");
user_pref("general.useragent.vendorSub", "");

user_pref("intl.accept_languages", "en-US,en");
user_pref("network.http.accept.default",  "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
user_pref("image.http.accept", "image/png,image/*;q=0.8,*/*;q=0.5");
user_pref("network.http.accept-encoding", "gzip, deflate");
user_pref("general.useragent.locale", "en-US");

user_pref("network.proxy.ftp", "127.0.0.1");
user_pref("network.proxy.ftp_port", 4001);
user_pref("network.proxy.gopher", "127.0.0.1");
user_pref("network.proxy.gopher_port", 4001);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 4001);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", 4001);
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 4001);
user_pref("network.proxy.type", 1);


